name: Setup Git UV

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read 

jobs:
  setup-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
        aws-region: ${{ secrets.REGION }}
    
    - name: Retrieve the Output for instance ID 
      run: |
        INSTANCE_ID=$(aws cloudformation describe-stacks --stack-name WindowHostStack --query "Stacks[0].Outputs[?OutputKey=='MyInstanceId'].OutputValue" --output text)
        echo "INSTANCE_ID is $INSTANCE_ID"
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

    - name: Run SSM Command
      run: | 
        COMMAND_ID=$(aws ssm send-command \
          --document-name "AWS-RunPowerShellScript" \
          --targets "Key=instanceids,Values=${{ env.INSTANCE_ID }}" \
          --parameters file://parameters.json \
          --timeout-seconds 120 \
          --query 'Command.CommandId' --output text)
         echo "Command ID: $COMMAND_ID"

         # Wait for the command to complete
         while true; do
           STATUS=$(aws ssm list-command-invocations --command-id $COMMAND_ID --query 'CommandInvocations[0].Status' --output text)
           echo "Current Status: $STATUS"
           if [[ "$STATUS" == "Success" || "$STATUS" == "Failed" ]]; then
             break
           fi
           sleep 10
         done

         echo "Command execution completed with status: $STATUS"
