name: Install git and packages

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:
  InstallationGitPackage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
        aws-region: ${{ secrets.REGION }}

    - name: Update AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Retrieve the Output for instance ID 
      run: |
        INSTANCE_ID=$(aws cloudformation describe-stacks --stack-name WindowHostStack --query "Stacks[0].Outputs[?OutputKey=='MyInstanceId'].OutputValue" --output text)
        echo "INSTANCE_ID is $INSTANCE_ID"
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

    - name: Create a SSM document
      run: |
        aws ssm create-document --name "WinGet_Test" --document-type "Command" --content '{
          "schemaVersion": "2.2",
          "description": "Download and install WinGet, then check versions",
          "mainSteps": [
            {
              "action": "aws:runPowerShellScript",
              "name": "installWinGetAndCheckVersions",
              "inputs": {
                "runCommand": [
                  "Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.11.430/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile C:\\Windows\\System32\\config\\systemprofile\\.local\\bin\\WinGet.msixbundle",
                  "Add-AppxPackage C:\\Windows\\System32\\config\\systemprofile\\.local\\bin\\WinGet.msixbundle",
                  "uv --version",
                  "winget --version"
                ]
              }
            }
          ]
        }'

    - name: Run SSM Command
      run: |
        aws ssm send-command \
          --document-name "WinGet_Test" \
          --targets "Key=instanceids,Values=${{ env.INSTANCE_ID }}" \
          --comment "Running WinGet_Test document" \
          --timeout-seconds 1200
